spring:
  datasource:
    username: root
    password: password
    url: jdbc:mariadb://localhost:3306/jwtdemo
  jpa:
    hibernate:
      ddl-auto: update

token:
  secret: 123456tt
  #  1 day
  expiration-time: 86400000
  prefix: Bearer-
  header-string: Authorization
  sign-up-url: /users

server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /jwtdemo

page-limit: 5